apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acm-appsets
  namespace: openshift-gitops
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"argoproj.io/v1alpha1","kind":"ApplicationSet","metadata":{"annotations":{},"creationTimestamp":"2021-12-03T11:41:52Z","generation":6,"name":"acm-appsets","namespace":"openshift-gitops","resourceVersion":"3001480","uid":"c500bc32-eec8-4775-bec4-68e420788a60"},"spec":{"generators":[{"clusterDecisionResource":{"configMapRef":"acm-placement","labelSelector":{"matchLabels":{"cluster.open-cluster-management.io/placement":"acm-appsets-placement"}},"requeueAfterSeconds":180}}],"template":{"metadata":{"name":"acm-appsets-{{name}}"},"spec":{"destination":{"namespace":"bgdk","server":"{{server}}"},"project":"default","source":{"path":"apps/bgd/overlays/bgdk","repoURL":"https://github.com/RedHat-EMEA-SSA-Team/ns-apps/","targetRevision":"single-app"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true}}}}}}
  creationTimestamp: 2023-02-21T16:12:58Z
  generation: 2
  resourceVersion: "565203"
  uid: 1fba8d3c-421f-4b79-80e4-3be614e5ec23
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: acm-appsets-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: acm-appsets-{{name}}
    spec:
      destination:
        namespace: bgdk
        server: "{{server}}"
      project: default
      source:
        path: apps/bgd/overlays/bgdk
        repoURL: https://github.com/RedHat-EMEA-SSA-Team/ns-apps/
        targetRevision: single-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
status:
  conditions:
    - lastTransitionTime: 2023-02-21T16:14:23Z
      message: Successfully generated parameters for all Applications
      reason: ApplicationSetUpToDate
      status: "False"
      type: ErrorOccurred
    - lastTransitionTime: 2023-02-21T16:14:23Z
      message: Successfully generated parameters for all Applications
      reason: ParametersGenerated
      status: "True"
      type: ParametersGenerated
    - lastTransitionTime: 2023-02-21T16:14:23Z
      message: ApplicationSet up to date
      reason: ApplicationSetUpToDate
      status: "True"
      type: ResourcesUpToDate
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acm-appsets-placement
  namespace: openshift-gitops
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"cluster.open-cluster-management.io/v1beta1","kind":"Placement","metadata":{"annotations":{},"name":"all-openshift-clusters","namespace":"openshift-gitops"},"spec":{"predicates":[{"requiredClusterSelector":{"labelSelector":{"matchExpressions":[{"key":"vendor","operator":"In","values":["OpenShift"]}]}}}]}}
  creationTimestamp: 2023-02-21T16:08:54Z
  generation: 1
  resourceVersion: "556040"
  uid: f84cb3ce-42d3-45f9-ab7a-453fa4fc1f15
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
status:
  conditions:
    - lastTransitionTime: 2023-02-21T16:08:54Z
      message: Placement configurations check pass
      reason: Succeedconfigured
      status: "False"
      type: PlacementMisconfigured
    - lastTransitionTime: 2023-02-21T16:08:54Z
      message: All cluster decisions scheduled
      reason: AllDecisionsScheduled
      status: "True"
      type: PlacementSatisfied
  numberOfSelectedClusters: 2
