apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: food-app
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - cluster: ocp4stage
            url: https://api.cluster-tqbqn.tqbqn.sandbox1817.opentlc.com:6443
          - cluster: ocp4dev
            url: https://api.cluster-4xhhm.4xhhm.sandbox1456.opentlc.com:6443
      clusterDecisionResource:
        requeueAfterSeconds: 180
  template:
    metadata:
      name: food-app-{{name}}
    spec:
      destination:
        namespace: devsecops
        server: "{{url}}"
      project: default
      source:
        path: overlays/{{cluster}}
        repoURL: https://github.com/gamagnolo/food-app-config
        targetRevision: HEAD
