apiVersion: v1
kind: Secret
metadata:
  name: pac-demo-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJkZW1vLXJlZ2lzdHJ5LXF1YXktcXVheS1kZW1vLmFwcHMub2NwNGh1Yi5zYW5kYm94OTYzLm9wZW50bGMuY29tIjogewogICAgICAiYXV0aCI6ICJjR0ZqTFdSbGJXOHRjR2x3Wld4cGJtVnpLM0JoWTE5a1pXMXZPalEwU2xOVVVVTXpRVFpPVGpORU1VVTBRMGxTTXpkTlJrbFlVVXhFT1VoVVNFOVlWRlE1VGpSVk1sQlNVbE15VDFJNFdETXdTVlJVV0VWWU5FWkRSa1k9IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
